
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-hpaimage
spec:
  selector:
    matchLabels:
      app: basic-hpaimage
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: basic-hpaimage
    spec:
      containers:
      - resources: 
          requests:
            cpu: "100m"
        name: basic-web-srv
        image: pradeepsukale/hpaimage:latest
